# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kafkaspark
spring.datasource.username=postgres
spring.datasource.password=postgres

# JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

# Port
server.port=8082