# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/kafkaspark
spring.datasource.username=postgres
spring.datasource.password=postgres

# Kafka
kafka.bootstrap.servers=localhost:9092
kafka.topic=persons

# RandomUser API
randomuser.api.url=https://randomuser.me/api/
randomuser.api.results=100